apiVersion: v1
kind: Service
metadata:
  name: parser
  labels:
    app: guestbook
    tier: parser
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: guestbook
    tier: parser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  labels:
    app: guestbook
    tier: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: parser
  template:
    metadata:
      labels:
        app: guestbook
        tier: parser
    spec:
      containers:
      - name: parser
        image: bschmitt769/kubernetes-demo-apps-parser:1.2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license-key
              key: license
        - name: NEW_RELIC_APP_NAME
          value: Workshop-Parser
        - name: NEW_RELIC_APP_NAME
          value: Workshop-Parser
        - name: NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED
          value: "true"
        - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
          value: "false"
          # tells the node.js app to pause at random intervals
        - name: LOOK_BUSY
          value: f
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
          - containerPort: 3000
