apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: guestbook
    tier: worker
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: guestbook
    tier: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: guestbook
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: worker
  template:
    metadata:
      labels:
        app: guestbook
        tier: worker
    spec:
      containers:
      - name: worker
        image: bschmitt769/kubernetes-demo-apps-worker:1.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 200Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license-key
              key: license
        - name: NEW_RELIC_APP_NAME
          value: Workshop-Worker
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
          - containerPort: 3000
